int power(int col, int i);
void genTable(int row, int col, int table[row][col]);
void copy(int col, int current[], const int last[]);
void flip(int col, int i, int table[]);
void push(int element);
int pop();
void clear();
void runFormula(int var[], char formula[], int output[]);
int add(int a, int b);
int findOps(const char formula[]);
int findIndex(char val);